import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import axios from 'axios';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const API_URL = process.env.EXPO_PUBLIC_API_URL;

export default function PaymentDetail() {
    const { id } = useLocalSearchParams();
    const router = useRouter();
    const [payment, setPayment] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchDetail = async () => {
            try {
                const token = await AsyncStorage.getItem('userToken');
                const response = await axios.get(`${API_URL}/tenant/payments/${id}`, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                setPayment(response.data);
            } catch (error) {
                console.error("Error Detail:", error.message);
            } finally {
                setLoading(false);
            }
        };
        fetchDetail();
    }, [id]);

    const formatRp = (num) => {
        if (!num) return "0";
        const rounded = Math.round(num); 
        return rounded.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
    };    

    const formatPeriod = (date) => {
        if(!date) return "";
        const d = new Date(date);
        return d.toLocaleDateString('id-ID', { month: 'long', year: 'numeric' });
    };

    if (loading) return (
        <View style={styles.center}><ActivityIndicator size="large" color="#0d9488" /></View>
    );

    if (!payment) return null;

    return (
        <SafeAreaView style={styles.container}>
            {/* Tombol Back */}
            <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                <Ionicons name="chevron-back" size={28} color="#134e4a" />
            </TouchableOpacity>

            <ScrollView 
                contentContainerStyle={styles.scrollContent}
                showsVerticalScrollIndicator={false}
            >
                <View style={styles.card}>
                    <View style={styles.circleAccent} />

                    <View style={styles.header}>
                        <Text style={styles.brandName}>Serrata Kost</Text>
                        <Text style={styles.title}>E-Kwitansi</Text>
                        {/* SUDAH DIPERBAIKI: div diganti View */}
                        <View style={styles.statusBadge}>
                            <Text style={styles.statusText}>● Lunas</Text>
                        </View>
                    </View>

                    <View style={styles.content}>
                        <View style={styles.infoGrid}>
                            <View style={styles.infoItem}>
                                <Text style={styles.label}>Penyewa</Text>
                                <Text style={styles.value}>{payment.tenant?.user?.name || payment.tenant?.name}</Text>
                            </View>
                            <View style={styles.infoItem}>
                                <Text style={styles.label}>Unit Kamar</Text>
                                <Text style={[styles.value, { color: '#0d9488' }]}>No. {payment.room?.room_number}</Text>
                            </View>
                            <View style={styles.infoItem}>
                                <Text style={styles.label}>Periode Pembayaran</Text>
                                <Text style={styles.value}>{formatPeriod(payment.period_month)}</Text>
                            </View>
                            <View style={styles.infoItem}>
                                <Text style={styles.label}>No. Invoice</Text>
                                <View style={styles.invoiceNoBox}>
                                    <Text style={styles.invoiceNoText}>#{payment.invoice_number}</Text>
                                </View>
                            </View>
                        </View>

                        <View style={styles.amountCard}>
                            <Text style={styles.totalLabel}>Total Diterima</Text>
                            <View style={styles.amountWrapper}>
                                <Text style={styles.currencyPrefix}>Rp</Text>
                                <Text style={styles.totalAmount}>{formatRp(payment.total)}</Text>
                            </View>
                        </View>

                        <View style={styles.divider} />

                        <View style={styles.footer}>
                            <Text style={styles.footerText}>
                                Generated by System {new Date().toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })}, {new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}
                            </Text>
                        </View>
                    </View>
                </View>
            </ScrollView>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f0f9f9' },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    backButton: { padding: 10, position: 'absolute', top: 10, left: 10, zIndex: 10 },
    scrollContent: { 
        flexGrow: 1, 
        justifyContent: 'center', 
        paddingHorizontal: 20,
        paddingBottom: 40 
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 32,
        width: '100%',
        maxWidth: 480,
        alignSelf: 'center',
        shadowColor: '#0d9488',
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.1,
        shadowRadius: 40,
        elevation: 10,
        overflow: 'hidden',
        position: 'relative',
    },
    circleAccent: {
        position: 'absolute',
        top: -50,
        right: -50,
        width: 150,
        height: 150,
        backgroundColor: 'rgba(20, 184, 166, 0.08)',
        borderRadius: 75,
    },
    header: { padding: 40, paddingBottom: 20 },
    brandName: { fontSize: 12, fontWeight: '800', color: '#0d9488', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 8 },
    title: { fontSize: 28, color: '#134e4a', fontWeight: '800', letterSpacing: -0.5 },
    statusBadge: {
        backgroundColor: '#f0fdf4',
        paddingVertical: 6,
        paddingHorizontal: 16,
        borderRadius: 100,
        alignSelf: 'flex-start',
        marginTop: 12,
        borderWidth: 1,
        borderColor: '#dcfce7',
    },
    statusText: { color: '#16a34a', fontSize: 12, fontWeight: '700' },
    content: { paddingHorizontal: 40, paddingBottom: 40 },
    divider: { height: 1, backgroundColor: '#f1f5f9', marginVertical: 30 },
    infoGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
    infoItem: { width: '48%', marginBottom: 25 },
    label: { fontSize: 10, color: '#94a3b8', fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
    value: { fontSize: 15, fontWeight: '700', color: '#334155' },
    invoiceNoBox: { backgroundColor: '#f8fafc', paddingVertical: 3, paddingHorizontal: 8, borderRadius: 6, alignSelf: 'flex-start' },
    invoiceNoText: { color: '#64748b', fontSize: 12, fontWeight: '600' },
    amountCard: {
        backgroundColor: '#f0fdfa',
        padding: 24,
        borderRadius: 24,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#ccfbf1',
        alignItems: 'center',
    },
    totalLabel: { fontSize: 11, color: '#115e59', fontWeight: '700', textTransform: 'uppercase', marginBottom: 6 },
    amountWrapper: { flexDirection: 'row', alignItems: 'baseline' },
    currencyPrefix: { fontSize: 14, color: '#115e59', fontWeight: '700', marginRight: 6 },
    totalAmount: { fontSize: 32, fontWeight: '800', color: '#115e59' },
    footer: { alignItems: 'center' },
    footerText: { fontSize: 10, color: '#94a3b8', fontWeight: '500' },
});